import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'de' | 'hi' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Additional translations for accessibility and voice components
const additionalTranslations: Record<Language, Record<string, string>> = {
  en: {
    'accessibleMode': 'Accessible Mode',
    'autoRead': 'Auto-read steps aloud',
    'language': 'Language',
    'listenToStep': 'Listen to this step',
    'loading': 'Loading',
    'emergencySummary': 'Emergency Summary',
    'copySummary': 'Copy Summary',
    // Voice Guide
    'voice.title': 'Voice Emergency Assistant',
    'voice.subtitle': 'Speak calmly. I\'ll guide you step by step.',
    'voice.listening': 'Listening...',
    'voice.processing': 'Processing...',
    'voice.answerNext': 'Please answer the next question',
    'voice.notSupported': 'Speech recognition is not supported in your browser.',
    'voice.typeFallback': 'Please type your response instead.',
    'voice.readQuestions': 'Read questions aloud',
    'voice.readInstructions': 'Read instructions aloud',
    'voice.disclaimer': 'This assistant provides guidance, not medical diagnosis.',
    'voice.restart': 'Restart Voice Guide',
    'voice.switchManual': 'Switch to Manual Steps',
    'voice.question.initial': 'What happened? Please describe the emergency situation.',
    'voice.question.conscious': 'Is the person conscious and responding?',
    'voice.question.breathing': 'Are they breathing normally?',
    'voice.question.bleeding': 'Is there any bleeding?',
    'voice.question.age': 'What is the approximate age of the person?',
    'voice.question.location': 'Where are you currently located?',
    'voice.option.yes': 'Yes',
    'voice.option.no': 'No',
    'voice.option.notSure': 'Not sure',
    'voice.option.breathingNormal': 'Normal',
    'voice.option.breathingDifficult': 'Difficult / Abnormal',
    'voice.option.notBreathing': 'Not breathing',
    'voice.option.nobleeding': 'None',
    'voice.option.minorBleeding': 'Minor',
    'voice.option.severeBleeding': 'Severe',
    'voice.option.infant': 'Infant (0-1)',
    'voice.option.child': 'Child (1-12)',
    'voice.option.adult': 'Adult (12-65)',
    'voice.option.elderly': 'Elderly (65+)',
  },
  de: {
    'accessibleMode': 'Barrierefreiheit',
    'autoRead': 'Schritte automatisch vorlesen',
    'language': 'Sprache',
    'listenToStep': 'Schritt anhören',
    'loading': 'Laden',
    'emergencySummary': 'Notfall-Zusammenfassung',
    'copySummary': 'Zusammenfassung kopieren',
    'voice.title': 'Sprach-Notfallassistent',
    'voice.subtitle': 'Sprechen Sie ruhig. Ich führe Sie Schritt für Schritt.',
    'voice.listening': 'Höre zu...',
    'voice.processing': 'Verarbeite...',
    'voice.answerNext': 'Bitte beantworten Sie die nächste Frage',
    'voice.notSupported': 'Spracherkennung wird in Ihrem Browser nicht unterstützt.',
    'voice.typeFallback': 'Bitte geben Sie Ihre Antwort stattdessen ein.',
    'voice.readQuestions': 'Fragen vorlesen',
    'voice.readInstructions': 'Anweisungen vorlesen',
    'voice.disclaimer': 'Dieser Assistent bietet Anleitung, keine medizinische Diagnose.',
    'voice.restart': 'Sprachführung neu starten',
    'voice.switchManual': 'Zu manuellen Schritten wechseln',
    'voice.question.initial': 'Was ist passiert? Beschreiben Sie die Notfallsituation.',
    'voice.question.conscious': 'Ist die Person bei Bewusstsein und reagiert?',
    'voice.question.breathing': 'Atmet sie normal?',
    'voice.question.bleeding': 'Gibt es Blutungen?',
    'voice.question.age': 'Wie alt ist die Person ungefähr?',
    'voice.question.location': 'Wo befinden Sie sich gerade?',
    'voice.option.yes': 'Ja',
    'voice.option.no': 'Nein',
    'voice.option.notSure': 'Unsicher',
    'voice.option.breathingNormal': 'Normal',
    'voice.option.breathingDifficult': 'Schwierig / Abnormal',
    'voice.option.notBreathing': 'Atmet nicht',
    'voice.option.nobleeding': 'Keine',
    'voice.option.minorBleeding': 'Leicht',
    'voice.option.severeBleeding': 'Stark',
    'voice.option.infant': 'Säugling (0-1)',
    'voice.option.child': 'Kind (1-12)',
    'voice.option.adult': 'Erwachsener (12-65)',
    'voice.option.elderly': 'Älterer (65+)',
  },
  hi: {
    'accessibleMode': 'सुलभता मोड',
    'autoRead': 'चरण स्वचालित पढ़ें',
    'language': 'भाषा',
    'listenToStep': 'इस चरण को सुनें',
    'loading': 'लोड हो रहा है',
    'emergencySummary': 'आपातकालीन सारांश',
    'copySummary': 'सारांश कॉपी करें',
    'voice.title': 'वॉइस इमरजेंसी असिस्टेंट',
    'voice.subtitle': 'शांति से बोलें। मैं आपको कदम दर कदम मार्गदर्शन करूंगा।',
    'voice.listening': 'सुन रहा हूं...',
    'voice.processing': 'प्रोसेस हो रहा है...',
    'voice.answerNext': 'कृपया अगले प्रश्न का उत्तर दें',
    'voice.notSupported': 'आपके ब्राउज़र में स्पीच रिकग्निशन सपोर्टेड नहीं है।',
    'voice.typeFallback': 'कृपया इसके बजाय अपना उत्तर टाइप करें।',
    'voice.readQuestions': 'प्रश्न ज़ोर से पढ़ें',
    'voice.readInstructions': 'निर्देश ज़ोर से पढ़ें',
    'voice.disclaimer': 'यह सहायक मार्गदर्शन प्रदान करता है, चिकित्सा निदान नहीं।',
    'voice.restart': 'वॉइस गाइड पुनः आरंभ करें',
    'voice.switchManual': 'मैनुअल स्टेप्स पर जाएं',
    'voice.question.initial': 'क्या हुआ? कृपया आपातकालीन स्थिति का वर्णन करें।',
    'voice.question.conscious': 'क्या व्यक्ति होश में है और प्रतिक्रिया कर रहा है?',
    'voice.question.breathing': 'क्या वे सामान्य रूप से सांस ले रहे हैं?',
    'voice.question.bleeding': 'क्या कोई खून बह रहा है?',
    'voice.question.age': 'व्यक्ति की अनुमानित उम्र क्या है?',
    'voice.question.location': 'आप वर्तमान में कहां हैं?',
    'voice.option.yes': 'हाँ',
    'voice.option.no': 'नहीं',
    'voice.option.notSure': 'पता नहीं',
    'voice.option.breathingNormal': 'सामान्य',
    'voice.option.breathingDifficult': 'कठिन / असामान्य',
    'voice.option.notBreathing': 'सांस नहीं ले रहा',
    'voice.option.nobleeding': 'कोई नहीं',
    'voice.option.minorBleeding': 'हल्का',
    'voice.option.severeBleeding': 'गंभीर',
    'voice.option.infant': 'शिशु (0-1)',
    'voice.option.child': 'बच्चा (1-12)',
    'voice.option.adult': 'वयस्क (12-65)',
    'voice.option.elderly': 'बुज़ुर्ग (65+)',
  },
  es: {
    'accessibleMode': 'Modo Accesible',
    'autoRead': 'Leer pasos en voz alta',
    'language': 'Idioma',
    'listenToStep': 'Escuchar este paso',
    'loading': 'Cargando',
    'emergencySummary': 'Resumen de Emergencia',
    'copySummary': 'Copiar Resumen',
    'voice.title': 'Asistente de Emergencia por Voz',
    'voice.subtitle': 'Habla con calma. Te guiaré paso a paso.',
    'voice.listening': 'Escuchando...',
    'voice.processing': 'Procesando...',
    'voice.answerNext': 'Por favor responde la siguiente pregunta',
    'voice.notSupported': 'El reconocimiento de voz no está soportado en tu navegador.',
    'voice.typeFallback': 'Por favor escribe tu respuesta.',
    'voice.readQuestions': 'Leer preguntas en voz alta',
    'voice.readInstructions': 'Leer instrucciones en voz alta',
    'voice.disclaimer': 'Este asistente proporciona orientación, no diagnóstico médico.',
    'voice.restart': 'Reiniciar Guía de Voz',
    'voice.switchManual': 'Cambiar a Pasos Manuales',
    'voice.question.initial': '¿Qué pasó? Describe la situación de emergencia.',
    'voice.question.conscious': '¿La persona está consciente y responde?',
    'voice.question.breathing': '¿Está respirando normalmente?',
    'voice.question.bleeding': '¿Hay algún sangrado?',
    'voice.question.age': '¿Cuál es la edad aproximada de la persona?',
    'voice.question.location': '¿Dónde estás actualmente?',
    'voice.option.yes': 'Sí',
    'voice.option.no': 'No',
    'voice.option.notSure': 'No estoy seguro',
    'voice.option.breathingNormal': 'Normal',
    'voice.option.breathingDifficult': 'Difícil / Anormal',
    'voice.option.notBreathing': 'No respira',
    'voice.option.nobleeding': 'Ninguno',
    'voice.option.minorBleeding': 'Menor',
    'voice.option.severeBleeding': 'Severo',
    'voice.option.infant': 'Bebé (0-1)',
    'voice.option.child': 'Niño (1-12)',
    'voice.option.adult': 'Adulto (12-65)',
    'voice.option.elderly': 'Anciano (65+)',
  },
  fr: {
    'accessibleMode': 'Mode Accessible',
    'autoRead': 'Lire les étapes à voix haute',
    'language': 'Langue',
    'listenToStep': 'Écouter cette étape',
    'loading': 'Chargement',
    'emergencySummary': 'Résumé d\'Urgence',
    'copySummary': 'Copier le Résumé',
    'voice.title': 'Assistant d\'Urgence Vocal',
    'voice.subtitle': 'Parlez calmement. Je vous guiderai étape par étape.',
    'voice.listening': 'Écoute en cours...',
    'voice.processing': 'Traitement...',
    'voice.answerNext': 'Veuillez répondre à la prochaine question',
    'voice.notSupported': 'La reconnaissance vocale n\'est pas supportée dans votre navigateur.',
    'voice.typeFallback': 'Veuillez taper votre réponse.',
    'voice.readQuestions': 'Lire les questions à haute voix',
    'voice.readInstructions': 'Lire les instructions à haute voix',
    'voice.disclaimer': 'Cet assistant fournit des conseils, pas de diagnostic médical.',
    'voice.restart': 'Redémarrer le Guide Vocal',
    'voice.switchManual': 'Passer aux Étapes Manuelles',
    'voice.question.initial': 'Que s\'est-il passé? Décrivez la situation d\'urgence.',
    'voice.question.conscious': 'La personne est-elle consciente et répond-elle?',
    'voice.question.breathing': 'Respire-t-elle normalement?',
    'voice.question.bleeding': 'Y a-t-il des saignements?',
    'voice.question.age': 'Quel est l\'âge approximatif de la personne?',
    'voice.question.location': 'Où êtes-vous actuellement?',
    'voice.option.yes': 'Oui',
    'voice.option.no': 'Non',
    'voice.option.notSure': 'Pas sûr',
    'voice.option.breathingNormal': 'Normal',
    'voice.option.breathingDifficult': 'Difficile / Anormal',
    'voice.option.notBreathing': 'Ne respire pas',
    'voice.option.nobleeding': 'Aucun',
    'voice.option.minorBleeding': 'Mineur',
    'voice.option.severeBleeding': 'Sévère',
    'voice.option.infant': 'Nourrisson (0-1)',
    'voice.option.child': 'Enfant (1-12)',
    'voice.option.adult': 'Adulte (12-65)',
    'voice.option.elderly': 'Personne âgée (65+)',
  },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.emergency': 'Emergency Help',
    'nav.nearby': 'Nearby Help',
    'nav.voice': 'Voice Guide',
    'nav.about': 'About',
    
    // Home page
    'home.title': 'Stay Calm. Act Fast.',
    'home.subtitle': 'Get guided help in the first 30 minutes.',
    'home.description': 'Step-by-step emergency actions + voice instructions + nearby help. Designed for panic situations, built for saving lives.',
    'home.cta.start': 'Start Emergency Help',
    'home.cta.voice': 'Speak to Assistant',
    'home.stat.window': 'Critical window',
    'home.stat.types': 'Emergency types',
    'home.stat.voice': 'Guided steps',
    
    // Citizen Mode
    'citizen.title': "What's the emergency?",
    'citizen.subtitle': 'Select the situation that best matches. We\'ll guide you step by step.',
    'citizen.nearby': 'Find Nearby Help',
    'citizen.nearby.desc': 'Hospitals, pharmacies, emergency services',
    'citizen.voice': 'Voice Assistant',
    'citizen.voice.desc': 'Hands-free emergency guidance',
    
    // Emergency categories
    'emergency.bleeding.title': 'Severe Bleeding / Cuts',
    'emergency.bleeding.desc': 'Heavy bleeding, deep cuts, wounds',
    'emergency.unconscious.title': 'Unconscious / Not Responding',
    'emergency.unconscious.desc': 'Person not waking up or responding',
    'emergency.breathing.title': 'Breathing Trouble / Asthma',
    'emergency.breathing.desc': 'Difficulty breathing, asthma attack',
    'emergency.chest.title': 'Chest Pain / Heart Attack',
    'emergency.chest.desc': 'Heart attack or stroke symptoms',
    'emergency.stroke.title': 'Stroke (FAST Test)',
    'emergency.stroke.desc': 'Face drooping, arm weakness, speech',
    'emergency.choking.title': 'Choking',
    'emergency.choking.desc': 'Airway obstruction in adults or children',
    'emergency.burns.title': 'Burns',
    'emergency.burns.desc': 'Thermal, chemical, or electrical burns',
    'emergency.seizure.title': 'Seizure',
    'emergency.seizure.desc': 'Convulsions and seizure episodes',
    'emergency.fracture.title': 'Fracture / Sprain',
    'emergency.fracture.desc': 'Broken bones, sprains, dislocations',
    'emergency.head.title': 'Head Injury / Concussion',
    'emergency.head.desc': 'Head trauma, concussion symptoms',
    'emergency.poison.title': 'Poisoning / Chemical Exposure',
    'emergency.poison.desc': 'Ingested poison or chemical contact',
    'emergency.allergy.title': 'Allergic Reaction / Anaphylaxis',
    'emergency.allergy.desc': 'Severe allergic reaction, swelling',
    'emergency.fever.title': 'Fever (Child/Adult)',
    'emergency.fever.desc': 'High temperature management',
    'emergency.electric.title': 'Electric Shock',
    'emergency.electric.desc': 'Electrical injury or shock',
    'emergency.drowning.title': 'Drowning / Near-Drowning',
    'emergency.drowning.desc': 'Water-related emergencies',
    
    // Flow UI
    'flow.step': 'Step',
    'flow.of': 'of',
    'flow.done': 'Done',
    'flow.cant': "I can't do this",
    'flow.next': 'Next',
    'flow.back': 'Back',
    'flow.exit': 'Exit',
    'flow.restart': 'Restart',
    'flow.summary': 'End & Summary',
    'flow.call': 'Call Emergency Services',
    'flow.listen': 'Listen to this step',
    'flow.autoread': 'Auto-read steps aloud',
    'flow.calm': 'Stay calm. Follow one step at a time.',
    
    // Accessibility
    'a11y.mode': 'Accessible Mode',
    'a11y.largetext': 'Larger text',
    'a11y.highcontrast': 'High contrast',
    'a11y.autoread': 'Auto-read enabled',
    'a11y.language': 'Language',
    
    // Summary
    'summary.title': 'Emergency Summary',
    'summary.share': 'Share this with emergency responders',
    'summary.type': 'Emergency Type',
    'summary.steps': 'Steps Completed',
    'summary.skipped': 'Steps Skipped',
    'summary.duration': 'Duration',
    'summary.priority': 'Priority Level',
    'summary.copy': 'Copy Summary',
    'summary.new': 'New Emergency',
    
    // Trust points
    'trust.nologin': 'No Login Required',
    'trust.nologin.desc': 'Instant access when every second counts. No accounts, no barriers.',
    'trust.panic': 'Panic-Proof Design',
    'trust.panic.desc': 'Large buttons, clear instructions, one step at a time.',
    'trust.privacy': 'Privacy First',
    'trust.privacy.desc': 'Your emergency data stays on your device. We don\'t track you.',
    
    // Common
    'common.start': 'Start',
    'common.viewmap': 'View Map',
    'common.minutes': 'min',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.emergency': 'Notfallhilfe',
    'nav.nearby': 'Hilfe in der Nähe',
    'nav.voice': 'Sprachführung',
    'nav.about': 'Über uns',
    'home.title': 'Ruhig bleiben. Schnell handeln.',
    'home.subtitle': 'Geführte Hilfe in den ersten 30 Minuten.',
    'home.description': 'Schritt-für-Schritt Notfallmaßnahmen + Sprachführung + Hilfe in der Nähe. Entwickelt für Paniksituationen.',
    'home.cta.start': 'Notfallhilfe starten',
    'home.cta.voice': 'Sprachassistent',
    'home.stat.window': 'Kritisches Fenster',
    'home.stat.types': 'Notfalltypen',
    'home.stat.voice': 'Geführte Schritte',
    'citizen.title': 'Was ist der Notfall?',
    'citizen.subtitle': 'Wählen Sie die passende Situation. Wir führen Sie Schritt für Schritt.',
    'citizen.nearby': 'Hilfe in der Nähe',
    'citizen.nearby.desc': 'Krankenhäuser, Apotheken, Notdienste',
    'citizen.voice': 'Sprachassistent',
    'citizen.voice.desc': 'Freihändige Notfallführung',
    'emergency.bleeding.title': 'Starke Blutung / Schnitte',
    'emergency.bleeding.desc': 'Starke Blutungen, tiefe Schnitte',
    'emergency.unconscious.title': 'Bewusstlos / Keine Reaktion',
    'emergency.unconscious.desc': 'Person wacht nicht auf',
    'emergency.breathing.title': 'Atemnot / Asthmaanfall',
    'emergency.breathing.desc': 'Schwierigkeiten beim Atmen',
    'emergency.chest.title': 'Brustschmerzen / Herzinfarkt',
    'emergency.chest.desc': 'Herzinfarkt-Symptome',
    'emergency.stroke.title': 'Schlaganfall (FAST-Test)',
    'emergency.stroke.desc': 'Gesichtslähmung, Armschwäche',
    'emergency.choking.title': 'Ersticken',
    'emergency.choking.desc': 'Atemwegsblockade',
    'emergency.burns.title': 'Verbrennungen',
    'emergency.burns.desc': 'Thermische, chemische Verbrennungen',
    'emergency.seizure.title': 'Krampfanfall',
    'emergency.seizure.desc': 'Krämpfe und Anfälle',
    'emergency.fracture.title': 'Bruch / Verstauchung',
    'emergency.fracture.desc': 'Gebrochene Knochen, Verstauchungen',
    'emergency.head.title': 'Kopfverletzung / Gehirnerschütterung',
    'emergency.head.desc': 'Kopftrauma-Symptome',
    'emergency.poison.title': 'Vergiftung / Chemikalien',
    'emergency.poison.desc': 'Gift eingenommen oder Kontakt',
    'emergency.allergy.title': 'Allergische Reaktion / Anaphylaxie',
    'emergency.allergy.desc': 'Schwere allergische Reaktion',
    'emergency.fever.title': 'Fieber (Kind/Erwachsener)',
    'emergency.fever.desc': 'Hohes Fieber behandeln',
    'emergency.electric.title': 'Stromschlag',
    'emergency.electric.desc': 'Elektrische Verletzung',
    'emergency.drowning.title': 'Ertrinken / Beinahe-Ertrinken',
    'emergency.drowning.desc': 'Wassernotfälle',
    'flow.step': 'Schritt',
    'flow.of': 'von',
    'flow.done': 'Fertig',
    'flow.cant': 'Das kann ich nicht',
    'flow.next': 'Weiter',
    'flow.back': 'Zurück',
    'flow.exit': 'Beenden',
    'flow.restart': 'Neustart',
    'flow.summary': 'Beenden & Zusammenfassung',
    'flow.call': 'Notruf wählen',
    'flow.listen': 'Diesen Schritt anhören',
    'flow.autoread': 'Schritte automatisch vorlesen',
    'flow.calm': 'Ruhig bleiben. Einen Schritt nach dem anderen.',
    'a11y.mode': 'Barrierefreiheit',
    'a11y.largetext': 'Größerer Text',
    'a11y.highcontrast': 'Hoher Kontrast',
    'a11y.autoread': 'Auto-Vorlesen aktiv',
    'a11y.language': 'Sprache',
    'summary.title': 'Notfall-Zusammenfassung',
    'summary.share': 'Teilen Sie dies mit Rettungskräften',
    'summary.type': 'Notfalltyp',
    'summary.steps': 'Schritte erledigt',
    'summary.skipped': 'Schritte übersprungen',
    'summary.duration': 'Dauer',
    'summary.priority': 'Priorität',
    'summary.copy': 'Zusammenfassung kopieren',
    'summary.new': 'Neuer Notfall',
    'trust.nologin': 'Kein Login nötig',
    'trust.nologin.desc': 'Sofortiger Zugang wenn jede Sekunde zählt.',
    'trust.panic': 'Panik-sicheres Design',
    'trust.panic.desc': 'Große Buttons, klare Anweisungen.',
    'trust.privacy': 'Datenschutz zuerst',
    'trust.privacy.desc': 'Ihre Daten bleiben auf Ihrem Gerät.',
    'common.start': 'Starten',
    'common.viewmap': 'Karte anzeigen',
    'common.minutes': 'Min',
  },
  hi: {
    'nav.home': 'होम',
    'nav.emergency': 'आपातकालीन सहायता',
    'nav.nearby': 'नज़दीकी मदद',
    'nav.voice': 'वॉइस गाइड',
    'nav.about': 'हमारे बारे में',
    'home.title': 'शांत रहें। तेज़ी से कार्य करें।',
    'home.subtitle': 'पहले 30 मिनट में मार्गदर्शित सहायता।',
    'home.description': 'चरण-दर-चरण आपातकालीन कार्रवाई + वॉइस निर्देश + नज़दीकी मदद।',
    'home.cta.start': 'आपातकालीन सहायता शुरू करें',
    'home.cta.voice': 'सहायक से बात करें',
    'home.stat.window': 'महत्वपूर्ण समय',
    'home.stat.types': 'आपातकाल प्रकार',
    'home.stat.voice': 'मार्गदर्शित चरण',
    'citizen.title': 'आपातकाल क्या है?',
    'citizen.subtitle': 'उपयुक्त स्थिति चुनें। हम आपका मार्गदर्शन करेंगे।',
    'citizen.nearby': 'नज़दीकी मदद',
    'citizen.nearby.desc': 'अस्पताल, फार्मेसी, आपातकालीन सेवाएं',
    'citizen.voice': 'वॉइस असिस्टेंट',
    'citizen.voice.desc': 'हैंड्स-फ्री मार्गदर्शन',
    'emergency.bleeding.title': 'गंभीर रक्तस्राव / कट',
    'emergency.bleeding.desc': 'भारी खून बहना, गहरे कट',
    'emergency.unconscious.title': 'बेहोश / प्रतिक्रिया नहीं',
    'emergency.unconscious.desc': 'व्यक्ति नहीं जाग रहा',
    'emergency.breathing.title': 'सांस की तकलीफ़ / अस्थमा',
    'emergency.breathing.desc': 'सांस लेने में कठिनाई',
    'emergency.chest.title': 'छाती में दर्द / दिल का दौरा',
    'emergency.chest.desc': 'दिल का दौरा के लक्षण',
    'emergency.stroke.title': 'स्ट्रोक (FAST टेस्ट)',
    'emergency.stroke.desc': 'चेहरा झुकना, बांह कमज़ोरी',
    'emergency.choking.title': 'दम घुटना',
    'emergency.choking.desc': 'श्वसन मार्ग में रुकावट',
    'emergency.burns.title': 'जलना',
    'emergency.burns.desc': 'थर्मल, रासायनिक जलना',
    'emergency.seizure.title': 'दौरा',
    'emergency.seizure.desc': 'ऐंठन और दौरे',
    'emergency.fracture.title': 'फ्रैक्चर / मोच',
    'emergency.fracture.desc': 'टूटी हड्डियां, मोच',
    'emergency.head.title': 'सिर की चोट / कंकशन',
    'emergency.head.desc': 'सिर में चोट के लक्षण',
    'emergency.poison.title': 'विषाक्तता / रासायनिक संपर्क',
    'emergency.poison.desc': 'ज़हर या रसायन संपर्क',
    'emergency.allergy.title': 'एलर्जी / एनाफिलेक्सिस',
    'emergency.allergy.desc': 'गंभीर एलर्जी प्रतिक्रिया',
    'emergency.fever.title': 'बुखार (बच्चा/वयस्क)',
    'emergency.fever.desc': 'उच्च तापमान प्रबंधन',
    'emergency.electric.title': 'बिजली का झटका',
    'emergency.electric.desc': 'विद्युत चोट',
    'emergency.drowning.title': 'डूबना',
    'emergency.drowning.desc': 'पानी से संबंधित आपात',
    'flow.step': 'चरण',
    'flow.of': 'का',
    'flow.done': 'पूर्ण',
    'flow.cant': 'मैं यह नहीं कर सकता',
    'flow.next': 'अगला',
    'flow.back': 'वापस',
    'flow.exit': 'बाहर',
    'flow.restart': 'पुनः आरंभ',
    'flow.summary': 'समाप्त और सारांश',
    'flow.call': 'आपातकालीन सेवाएं कॉल करें',
    'flow.listen': 'इस चरण को सुनें',
    'flow.autoread': 'चरण स्वचालित पढ़ें',
    'flow.calm': 'शांत रहें। एक समय में एक चरण।',
    'a11y.mode': 'सुलभता मोड',
    'a11y.largetext': 'बड़ा टेक्स्ट',
    'a11y.highcontrast': 'उच्च कंट्रास्ट',
    'a11y.autoread': 'ऑटो-रीड सक्षम',
    'a11y.language': 'भाषा',
    'summary.title': 'आपातकालीन सारांश',
    'summary.share': 'बचावकर्ताओं के साथ साझा करें',
    'summary.type': 'आपातकाल प्रकार',
    'summary.steps': 'पूर्ण चरण',
    'summary.skipped': 'छोड़े गए चरण',
    'summary.duration': 'अवधि',
    'summary.priority': 'प्राथमिकता',
    'summary.copy': 'सारांश कॉपी करें',
    'summary.new': 'नया आपातकाल',
    'trust.nologin': 'लॉगिन आवश्यक नहीं',
    'trust.nologin.desc': 'तत्काल पहुंच।',
    'trust.panic': 'पैनिक-प्रूफ डिज़ाइन',
    'trust.panic.desc': 'बड़े बटन, स्पष्ट निर्देश।',
    'trust.privacy': 'गोपनीयता पहले',
    'trust.privacy.desc': 'आपका डेटा आपके डिवाइस पर रहता है।',
    'common.start': 'शुरू करें',
    'common.viewmap': 'मानचित्र देखें',
    'common.minutes': 'मिनट',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.emergency': 'Ayuda de Emergencia',
    'nav.nearby': 'Ayuda Cercana',
    'nav.voice': 'Guía de Voz',
    'nav.about': 'Acerca de',
    'home.title': 'Mantén la calma. Actúa rápido.',
    'home.subtitle': 'Ayuda guiada en los primeros 30 minutos.',
    'home.description': 'Acciones de emergencia paso a paso + instrucciones de voz + ayuda cercana.',
    'home.cta.start': 'Iniciar Ayuda de Emergencia',
    'home.cta.voice': 'Hablar con Asistente',
    'home.stat.window': 'Ventana crítica',
    'home.stat.types': 'Tipos de emergencia',
    'home.stat.voice': 'Pasos guiados',
    'citizen.title': '¿Cuál es la emergencia?',
    'citizen.subtitle': 'Selecciona la situación que coincida. Te guiaremos paso a paso.',
    'citizen.nearby': 'Ayuda Cercana',
    'citizen.nearby.desc': 'Hospitales, farmacias, servicios de emergencia',
    'citizen.voice': 'Asistente de Voz',
    'citizen.voice.desc': 'Guía de emergencia manos libres',
    'emergency.bleeding.title': 'Sangrado Severo / Cortes',
    'emergency.bleeding.desc': 'Sangrado abundante, cortes profundos',
    'emergency.unconscious.title': 'Inconsciente / Sin Respuesta',
    'emergency.unconscious.desc': 'Persona que no despierta',
    'emergency.breathing.title': 'Problemas Respiratorios / Asma',
    'emergency.breathing.desc': 'Dificultad para respirar',
    'emergency.chest.title': 'Dolor de Pecho / Infarto',
    'emergency.chest.desc': 'Síntomas de ataque cardíaco',
    'emergency.stroke.title': 'Derrame (Test FAST)',
    'emergency.stroke.desc': 'Caída facial, debilidad de brazo',
    'emergency.choking.title': 'Atragantamiento',
    'emergency.choking.desc': 'Obstrucción de vías respiratorias',
    'emergency.burns.title': 'Quemaduras',
    'emergency.burns.desc': 'Quemaduras térmicas, químicas',
    'emergency.seizure.title': 'Convulsión',
    'emergency.seizure.desc': 'Convulsiones y ataques',
    'emergency.fracture.title': 'Fractura / Esguince',
    'emergency.fracture.desc': 'Huesos rotos, esguinces',
    'emergency.head.title': 'Lesión de Cabeza / Conmoción',
    'emergency.head.desc': 'Síntomas de trauma craneal',
    'emergency.poison.title': 'Envenenamiento / Químicos',
    'emergency.poison.desc': 'Veneno ingerido o contacto',
    'emergency.allergy.title': 'Reacción Alérgica / Anafilaxia',
    'emergency.allergy.desc': 'Reacción alérgica severa',
    'emergency.fever.title': 'Fiebre (Niño/Adulto)',
    'emergency.fever.desc': 'Manejo de temperatura alta',
    'emergency.electric.title': 'Descarga Eléctrica',
    'emergency.electric.desc': 'Lesión eléctrica',
    'emergency.drowning.title': 'Ahogamiento',
    'emergency.drowning.desc': 'Emergencias relacionadas con agua',
    'flow.step': 'Paso',
    'flow.of': 'de',
    'flow.done': 'Hecho',
    'flow.cant': 'No puedo hacerlo',
    'flow.next': 'Siguiente',
    'flow.back': 'Atrás',
    'flow.exit': 'Salir',
    'flow.restart': 'Reiniciar',
    'flow.summary': 'Terminar y Resumen',
    'flow.call': 'Llamar Servicios de Emergencia',
    'flow.listen': 'Escuchar este paso',
    'flow.autoread': 'Leer pasos en voz alta',
    'flow.calm': 'Mantén la calma. Un paso a la vez.',
    'a11y.mode': 'Modo Accesible',
    'a11y.largetext': 'Texto grande',
    'a11y.highcontrast': 'Alto contraste',
    'a11y.autoread': 'Lectura automática',
    'a11y.language': 'Idioma',
    'summary.title': 'Resumen de Emergencia',
    'summary.share': 'Comparte con los respondedores',
    'summary.type': 'Tipo de Emergencia',
    'summary.steps': 'Pasos Completados',
    'summary.skipped': 'Pasos Omitidos',
    'summary.duration': 'Duración',
    'summary.priority': 'Nivel de Prioridad',
    'summary.copy': 'Copiar Resumen',
    'summary.new': 'Nueva Emergencia',
    'trust.nologin': 'Sin Inicio de Sesión',
    'trust.nologin.desc': 'Acceso instantáneo cuando cada segundo cuenta.',
    'trust.panic': 'Diseño Anti-Pánico',
    'trust.panic.desc': 'Botones grandes, instrucciones claras.',
    'trust.privacy': 'Privacidad Primero',
    'trust.privacy.desc': 'Tus datos permanecen en tu dispositivo.',
    'common.start': 'Iniciar',
    'common.viewmap': 'Ver Mapa',
    'common.minutes': 'min',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.emergency': "Aide d'Urgence",
    'nav.nearby': 'Aide à Proximité',
    'nav.voice': 'Guide Vocal',
    'nav.about': 'À Propos',
    'home.title': 'Restez calme. Agissez vite.',
    'home.subtitle': 'Aide guidée dans les 30 premières minutes.',
    'home.description': "Actions d'urgence étape par étape + instructions vocales + aide à proximité.",
    'home.cta.start': "Commencer l'Aide d'Urgence",
    'home.cta.voice': "Parler à l'Assistant",
    'home.stat.window': 'Fenêtre critique',
    'home.stat.types': "Types d'urgence",
    'home.stat.voice': 'Étapes guidées',
    'citizen.title': "Quelle est l'urgence?",
    'citizen.subtitle': 'Sélectionnez la situation correspondante. Nous vous guiderons.',
    'citizen.nearby': 'Aide à Proximité',
    'citizen.nearby.desc': "Hôpitaux, pharmacies, services d'urgence",
    'citizen.voice': 'Assistant Vocal',
    'citizen.voice.desc': "Guidage d'urgence mains libres",
    'emergency.bleeding.title': 'Saignement Sévère / Coupures',
    'emergency.bleeding.desc': 'Saignement abondant, coupures profondes',
    'emergency.unconscious.title': 'Inconscient / Sans Réponse',
    'emergency.unconscious.desc': 'Personne qui ne se réveille pas',
    'emergency.breathing.title': 'Problèmes Respiratoires / Asthme',
    'emergency.breathing.desc': 'Difficulté à respirer',
    'emergency.chest.title': 'Douleur Thoracique / Crise Cardiaque',
    'emergency.chest.desc': 'Symptômes de crise cardiaque',
    'emergency.stroke.title': 'AVC (Test FAST)',
    'emergency.stroke.desc': 'Affaissement du visage, faiblesse du bras',
    'emergency.choking.title': 'Étouffement',
    'emergency.choking.desc': 'Obstruction des voies respiratoires',
    'emergency.burns.title': 'Brûlures',
    'emergency.burns.desc': 'Brûlures thermiques, chimiques',
    'emergency.seizure.title': 'Crise Convulsive',
    'emergency.seizure.desc': 'Convulsions et crises',
    'emergency.fracture.title': 'Fracture / Entorse',
    'emergency.fracture.desc': 'Os cassés, entorses',
    'emergency.head.title': 'Traumatisme Crânien / Commotion',
    'emergency.head.desc': 'Symptômes de trauma crânien',
    'emergency.poison.title': 'Empoisonnement / Produits Chimiques',
    'emergency.poison.desc': 'Poison ingéré ou contact',
    'emergency.allergy.title': 'Réaction Allergique / Anaphylaxie',
    'emergency.allergy.desc': 'Réaction allergique sévère',
    'emergency.fever.title': 'Fièvre (Enfant/Adulte)',
    'emergency.fever.desc': 'Gestion de la température élevée',
    'emergency.electric.title': 'Choc Électrique',
    'emergency.electric.desc': 'Blessure électrique',
    'emergency.drowning.title': 'Noyade / Quasi-Noyade',
    'emergency.drowning.desc': "Urgences liées à l'eau",
    'flow.step': 'Étape',
    'flow.of': 'sur',
    'flow.done': 'Fait',
    'flow.cant': 'Je ne peux pas',
    'flow.next': 'Suivant',
    'flow.back': 'Retour',
    'flow.exit': 'Quitter',
    'flow.restart': 'Recommencer',
    'flow.summary': 'Terminer et Résumé',
    'flow.call': "Appeler les Services d'Urgence",
    'flow.listen': 'Écouter cette étape',
    'flow.autoread': 'Lire les étapes à haute voix',
    'flow.calm': 'Restez calme. Une étape à la fois.',
    'a11y.mode': 'Mode Accessible',
    'a11y.largetext': 'Texte agrandi',
    'a11y.highcontrast': 'Contraste élevé',
    'a11y.autoread': 'Lecture automatique',
    'a11y.language': 'Langue',
    'summary.title': "Résumé d'Urgence",
    'summary.share': 'Partagez avec les secouristes',
    'summary.type': "Type d'Urgence",
    'summary.steps': 'Étapes Complétées',
    'summary.skipped': 'Étapes Ignorées',
    'summary.duration': 'Durée',
    'summary.priority': 'Niveau de Priorité',
    'summary.copy': 'Copier le Résumé',
    'summary.new': 'Nouvelle Urgence',
    'trust.nologin': 'Sans Connexion',
    'trust.nologin.desc': 'Accès instantané quand chaque seconde compte.',
    'trust.panic': 'Design Anti-Panique',
    'trust.panic.desc': 'Grands boutons, instructions claires.',
    'trust.privacy': 'Confidentialité',
    'trust.privacy.desc': 'Vos données restent sur votre appareil.',
    'common.start': 'Commencer',
    'common.viewmap': 'Voir la Carte',
    'common.minutes': 'min',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || additionalTranslations[language]?.[key] || translations.en[key] || additionalTranslations.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  de: 'Deutsch',
  hi: 'हिंदी',
  es: 'Español',
  fr: 'Français',
};
