import { KitItem } from '@/data/firstAidKitData';
import KitItemCard from './KitItemCard';
import { Button } from '@/components/ui/button';
import { Download, Save, GraduationCap, Package } from 'lucide-react';
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';

interface KitResultsListProps {
  essential: KitItem[];
  ageSpecific: KitItem[];
  riskSpecific: KitItem[];
  optional: KitItem[];
  onSelectItem: (item: KitItem) => void;
  onStartTraining: () => void;
}

const KitResultsList = ({
  essential,
  ageSpecific,
  riskSpecific,
  optional,
  onSelectItem,
  onStartTraining,
}: KitResultsListProps) => {
  const { toast } = useToast();
  const [isSaved, setIsSaved] = useState(false);
  
  const totalItems = essential.length + ageSpecific.length + riskSpecific.length + optional.length;

  const handleDownload = () => {
    // Generate a text checklist
    const lines = [
      '📋 YOUR PERSONALIZED FIRST AID KIT',
      '=' .repeat(40),
      '',
      '✅ ESSENTIAL ITEMS',
      ...essential.map(item => `  □ ${item.name} - ${item.whyNeeded}`),
      '',
    ];

    if (ageSpecific.length > 0) {
      lines.push('👶 AGE-SPECIFIC ITEMS');
      lines.push(...ageSpecific.map(item => `  □ ${item.name} - ${item.whyNeeded}`));
      lines.push('');
    }

    if (riskSpecific.length > 0) {
      lines.push('⚡ RISK-SPECIFIC ITEMS');
      lines.push(...riskSpecific.map(item => `  □ ${item.name} - ${item.whyNeeded}`));
      lines.push('');
    }

    if (optional.length > 0) {
      lines.push('💡 RECOMMENDED ADD-ONS');
      lines.push(...optional.map(item => `  □ ${item.name} - ${item.whyNeeded}`));
      lines.push('');
    }

    lines.push('=' .repeat(40));
    lines.push('Generated by First30.ai');
    lines.push('Remember: This is guidance, not medical diagnosis.');

    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'first-aid-kit-checklist.txt';
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Checklist Downloaded",
      description: "Your personalized kit checklist has been saved.",
    });
  };

  const handleSave = () => {
    // In a real app, this would save to user account/localStorage
    localStorage.setItem('savedFirstAidKit', JSON.stringify({
      essential: essential.map(i => i.id),
      ageSpecific: ageSpecific.map(i => i.id),
      riskSpecific: riskSpecific.map(i => i.id),
      optional: optional.map(i => i.id),
      savedAt: new Date().toISOString(),
    }));
    setIsSaved(true);
    toast({
      title: "Kit Saved",
      description: "Your personalized kit has been saved locally.",
    });
  };

  const renderSection = (title: string, items: KitItem[], icon: React.ReactNode) => {
    if (items.length === 0) return null;
    
    return (
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-4">
          {icon}
          <h3 className="text-xl font-semibold text-foreground">{title}</h3>
          <span className="text-sm text-muted-foreground">({items.length} items)</span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {items.map(item => (
            <KitItemCard
              key={item.id}
              item={item}
              onLearnMore={() => onSelectItem(item)}
            />
          ))}
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-5xl mx-auto">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-20 h-20 rounded-2xl bg-primary/15 flex items-center justify-center mx-auto mb-4">
          <Package className="w-10 h-10 text-primary" />
        </div>
        <h2 className="text-3xl font-bold text-foreground mb-2">
          Your Personalized First Aid Kit
        </h2>
        <p className="text-lg text-muted-foreground mb-6">
          {totalItems} items recommended based on your assessment
        </p>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Button onClick={handleDownload} variant="outline" className="gap-2">
            <Download className="w-4 h-4" />
            Download Checklist
          </Button>
          <Button 
            onClick={handleSave} 
            variant="outline" 
            className="gap-2"
            disabled={isSaved}
          >
            <Save className="w-4 h-4" />
            {isSaved ? 'Saved!' : 'Save My Kit'}
          </Button>
          <Button onClick={onStartTraining} className="gap-2 bg-primary hover:bg-primary/90">
            <GraduationCap className="w-4 h-4" />
            Start Training
          </Button>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="premium-card p-4 mb-8 border-l-4 border-l-amber-500 bg-amber-500/5">
        <p className="text-sm text-muted-foreground">
          <strong className="text-foreground">Safety Note:</strong> This guidance is for preparedness 
          and education, not medical diagnosis. Do not prescribe or administer any medication without 
          proper authorization. Always consult healthcare professionals.
        </p>
      </div>

      {/* Kit Sections */}
      {renderSection(
        'Essential Items', 
        essential,
        <div className="w-8 h-8 rounded-lg bg-primary/15 flex items-center justify-center">
          <span className="text-lg">✅</span>
        </div>
      )}

      {renderSection(
        'Age-Specific Items', 
        ageSpecific,
        <div className="w-8 h-8 rounded-lg bg-cyan-500/15 flex items-center justify-center">
          <span className="text-lg">👶</span>
        </div>
      )}

      {renderSection(
        'Risk-Specific Items', 
        riskSpecific,
        <div className="w-8 h-8 rounded-lg bg-amber-500/15 flex items-center justify-center">
          <span className="text-lg">⚡</span>
        </div>
      )}

      {renderSection(
        'Recommended Add-ons', 
        optional,
        <div className="w-8 h-8 rounded-lg bg-secondary flex items-center justify-center">
          <span className="text-lg">💡</span>
        </div>
      )}
    </div>
  );
};

export default KitResultsList;
