import { useState } from 'react';
import { Copy, Check, FileText, Clock, CheckCircle, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { CollectedInput } from '@/types/emergency';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

interface EmergencySummaryCardProps {
  category: string;
  collectedInputs: CollectedInput[];
  stepsCompleted: string[];
  totalSteps: number;
  duration: number;
  className?: string;
}

const EmergencySummaryCard = ({
  category,
  collectedInputs,
  stepsCompleted,
  totalSteps,
  duration,
  className,
}: EmergencySummaryCardProps) => {
  const [copied, setCopied] = useState(false);
  const { t } = useLanguage();

  const formatDuration = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const generateSummaryText = (): string => {
    let summary = `=== ${t('emergencySummary')} ===\n\n`;
    summary += `Emergency Type: ${category}\n`;
    summary += `Duration: ${formatDuration(duration)}\n`;
    summary += `Steps Completed: ${stepsCompleted.length}/${totalSteps}\n\n`;
    
    if (collectedInputs.length > 0) {
      summary += `--- Key Information ---\n`;
      collectedInputs.forEach(input => {
        summary += `• ${input.question}: ${input.answer}\n`;
      });
      summary += '\n';
    }

    summary += `--- Steps Completed ---\n`;
    stepsCompleted.forEach((step, index) => {
      summary += `${index + 1}. ${step}\n`;
    });

    summary += `\nGenerated by First30.ai - ${new Date().toLocaleString()}`;
    
    return summary;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummaryText());
      setCopied(true);
      toast({
        title: 'Copied!',
        description: 'Emergency summary copied to clipboard',
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: 'Copy failed',
        description: 'Please try again',
        variant: 'destructive',
      });
    }
  };

  return (
    <div className={cn('premium-card p-5', className)}>
      <div className="flex items-center gap-2 mb-4">
        <FileText className="w-5 h-5 text-primary" />
        <h3 className="font-semibold text-foreground">{t('emergencySummary')}</h3>
      </div>

      <div className="space-y-3 mb-4">
        {/* Emergency Type */}
        <div className="flex items-center gap-2 text-sm">
          <AlertCircle className="w-4 h-4 text-muted-foreground" />
          <span className="text-muted-foreground">Type:</span>
          <span className="font-medium text-foreground">{category}</span>
        </div>

        {/* Duration */}
        <div className="flex items-center gap-2 text-sm">
          <Clock className="w-4 h-4 text-muted-foreground" />
          <span className="text-muted-foreground">Duration:</span>
          <span className="font-medium text-foreground">{formatDuration(duration)}</span>
        </div>

        {/* Steps */}
        <div className="flex items-center gap-2 text-sm">
          <CheckCircle className="w-4 h-4 text-muted-foreground" />
          <span className="text-muted-foreground">Steps:</span>
          <span className="font-medium text-foreground">
            {stepsCompleted.length}/{totalSteps} completed
          </span>
        </div>

        {/* Key Answers */}
        {collectedInputs.length > 0 && (
          <div className="pt-2 border-t border-border/50">
            <p className="text-sm text-muted-foreground mb-2">Key Answers:</p>
            <div className="space-y-1">
              {collectedInputs.slice(0, 4).map((input, index) => (
                <div key={index} className="text-sm">
                  <span className="text-muted-foreground">{input.question}:</span>{' '}
                  <span className="font-medium text-foreground">{input.answer}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <Button
        onClick={handleCopy}
        className="w-full gap-2"
        variant={copied ? 'default' : 'outline'}
      >
        {copied ? (
          <>
            <Check className="w-4 h-4" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            {t('copySummary')}
          </>
        )}
      </Button>
    </div>
  );
};

export default EmergencySummaryCard;
