import { 
  Clock, 
  MapPin, 
  CheckCircle2, 
  Copy, 
  Printer,
  Share2,
  Droplets,
  Wind,
  Heart,
  Flame,
  AlertCircle,
  Zap,
  XCircle,
  FileText,
  LucideIcon
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { EmergencySummaryData } from '@/types/emergency';
import PriorityBadge from '@/components/dispatcher/PriorityBadge';

interface SummaryCardProps {
  data: EmergencySummaryData;
  onNewEmergency: () => void;
}

const iconMap: Record<string, LucideIcon> = {
  droplets: Droplets,
  wind: Wind,
  heart: Heart,
  flame: Flame,
  'alert-circle': AlertCircle,
  zap: Zap,
};

const SummaryCard = ({ data, onNewEmergency }: SummaryCardProps) => {
  const IconComponent = iconMap[data.categoryIcon] || AlertCircle;

  const formatDuration = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    if (mins === 0) return `${secs} seconds`;
    return `${mins} min ${secs} sec`;
  };

  const formatTime = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const formatDate = (date: Date): string => {
    return date.toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const generateSummaryText = (): string => {
    const observations = data.keyObservations?.length > 0 
      ? data.keyObservations.map(o => `• ${o}`).join('\n')
      : 'None recorded';
    
    const actions = data.actionsTaken?.length > 0
      ? data.actionsTaken.map(a => `✓ ${a}`).join('\n')
      : 'None completed';

    return `
═══════════════════════════════════════
   EMERGENCY HANDOFF CARD - First30.ai
═══════════════════════════════════════

EMERGENCY TYPE: ${data.category}
PRIORITY: ${data.calculatedPriority} (${
      data.calculatedPriority === 'P1' ? 'CRITICAL' :
      data.calculatedPriority === 'P2' ? 'URGENT' :
      data.calculatedPriority === 'P3' ? 'MODERATE' : 'LOW'
    })

DATE: ${formatDate(data.startTime)}
START TIME: ${formatTime(data.startTime)}
DURATION: ${formatDuration(data.duration)}

───────────────────────────────────────
KEY OBSERVATIONS:
${observations}

───────────────────────────────────────
ACTIONS TAKEN (${data.stepsCompleted?.length || 0}/${data.totalSteps}):
${actions}

${data.stepsSkipped?.length > 0 ? `
STEPS SKIPPED:
${data.stepsSkipped.map(s => `⊘ ${s}`).join('\n')}
` : ''}
───────────────────────────────────────
Generated by First30.ai
Emergency Guidance Platform
    `.trim();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummaryText());
      toast.success('Summary copied to clipboard!');
    } catch (err) {
      toast.error('Failed to copy summary');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Emergency Summary - ${data.category}`,
          text: generateSummaryText(),
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      handleCopy();
    }
  };

  return (
    <div className="glass-card-strong p-6 md:p-8 print:bg-white print:text-black">
      {/* Header with Priority */}
      <div className="flex items-start justify-between mb-6">
        <div className="flex items-center gap-4">
          <div className={`w-16 h-16 rounded-2xl flex items-center justify-center ${
            data.calculatedPriority === 'P1' ? 'bg-emergency/20' :
            data.calculatedPriority === 'P2' ? 'bg-orange-500/20' :
            'bg-primary/20'
          }`}>
            <IconComponent className={`w-9 h-9 ${
              data.calculatedPriority === 'P1' ? 'text-emergency' :
              data.calculatedPriority === 'P2' ? 'text-orange-400' :
              'text-primary'
            }`} />
          </div>
          <div>
            <h2 className="text-heading-3 text-foreground">{data.category}</h2>
            <p className="text-sm text-muted-foreground">Emergency Handoff Card</p>
          </div>
        </div>
        <PriorityBadge priority={data.calculatedPriority} />
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
        <div className="glass-card p-3 text-center">
          <Clock className="w-5 h-5 text-muted-foreground mx-auto mb-1" />
          <p className="text-lg font-bold text-foreground">{formatDuration(data.duration)}</p>
          <p className="text-xs text-muted-foreground">Duration</p>
        </div>
        <div className="glass-card p-3 text-center">
          <CheckCircle2 className="w-5 h-5 text-success mx-auto mb-1" />
          <p className="text-lg font-bold text-foreground">{data.stepsCompleted?.length || 0}/{data.totalSteps}</p>
          <p className="text-xs text-muted-foreground">Steps</p>
        </div>
        <div className="glass-card p-3 text-center">
          <Clock className="w-5 h-5 text-muted-foreground mx-auto mb-1" />
          <p className="text-lg font-bold text-foreground">{formatTime(data.startTime)}</p>
          <p className="text-xs text-muted-foreground">Started</p>
        </div>
        <div className="glass-card p-3 text-center">
          <MapPin className="w-5 h-5 text-muted-foreground mx-auto mb-1" />
          <p className="text-sm font-bold text-foreground truncate">{data.location || '—'}</p>
          <p className="text-xs text-muted-foreground">Location</p>
        </div>
      </div>

      {/* Key Observations */}
      {data.keyObservations && data.keyObservations.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
            <FileText className="w-4 h-4 text-primary" />
            Key Observations
          </h3>
          <div className="glass-card p-4 space-y-2">
            {data.keyObservations.map((obs, index) => (
              <p key={index} className="text-sm text-muted-foreground">
                • {obs}
              </p>
            ))}
          </div>
        </div>
      )}

      {/* Actions Taken */}
      {data.actionsTaken && data.actionsTaken.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-success" />
            Actions Taken
          </h3>
          <div className="flex flex-wrap gap-2">
            {data.actionsTaken.map((action, index) => (
              <span
                key={index}
                className="px-3 py-1.5 rounded-lg bg-success/10 text-success text-sm border border-success/20"
              >
                ✓ {action}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Steps Skipped */}
      {data.stepsSkipped && data.stepsSkipped.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
            <XCircle className="w-4 h-4 text-muted-foreground" />
            Steps Skipped
          </h3>
          <div className="flex flex-wrap gap-2">
            {data.stepsSkipped.map((step, index) => (
              <span
                key={index}
                className="px-3 py-1.5 rounded-lg bg-muted/50 text-muted-foreground text-sm"
              >
                {step}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Share Actions */}
      <div className="flex flex-col sm:flex-row gap-3 print:hidden">
        <Button
          onClick={handleCopy}
          className="flex-1 h-12 bg-primary hover:bg-primary/90 rounded-xl font-semibold"
        >
          <Copy className="w-5 h-5 mr-2" />
          Copy Summary
        </Button>
        <Button
          onClick={handleShare}
          variant="outline"
          className="flex-1 h-12 rounded-xl"
        >
          <Share2 className="w-5 h-5 mr-2" />
          Share
        </Button>
        <Button
          onClick={handlePrint}
          variant="outline"
          className="h-12 rounded-xl"
        >
          <Printer className="w-5 h-5" />
        </Button>
      </div>

      {/* New Emergency */}
      <div className="mt-4 pt-4 border-t border-border print:hidden">
        <Button
          onClick={onNewEmergency}
          variant="ghost"
          className="w-full h-12 text-muted-foreground hover:text-foreground"
        >
          Start New Emergency
        </Button>
      </div>
    </div>
  );
};

export default SummaryCard;
