import { 
  Clock, 
  MapPin, 
  CheckCircle2, 
  Copy, 
  Printer,
  Share2,
  Droplets,
  Wind,
  Heart,
  Flame,
  AlertCircle,
  Zap,
  LucideIcon
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { EmergencySummaryData, Priority } from '@/types/emergency';
import PriorityBadge from '@/components/dispatcher/PriorityBadge';

interface SummaryCardProps {
  data: EmergencySummaryData;
  onNewEmergency: () => void;
}

const iconMap: Record<string, LucideIcon> = {
  droplets: Droplets,
  wind: Wind,
  heart: Heart,
  flame: Flame,
  'alert-circle': AlertCircle,
  zap: Zap,
};

const SummaryCard = ({ data, onNewEmergency }: SummaryCardProps) => {
  const IconComponent = iconMap[data.categoryIcon] || AlertCircle;

  const formatDuration = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    if (mins === 0) return `${secs} seconds`;
    return `${mins} min ${secs} sec`;
  };

  const formatTime = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const generateSummaryText = (): string => {
    return `
EMERGENCY SUMMARY - First30.ai
================================
Emergency Type: ${data.category}
Priority Level: ${data.priority}
Start Time: ${formatTime(data.startTime)}
End Time: ${formatTime(data.endTime)}
Duration: ${formatDuration(data.duration)}
Steps Completed: ${data.stepsCompleted.length} of ${data.totalSteps}
${data.location ? `Location: ${data.location}` : ''}

Generated by First30.ai - Emergency Guidance Platform
    `.trim();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummaryText());
      toast.success('Summary copied to clipboard');
    } catch (err) {
      toast.error('Failed to copy summary');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Emergency Summary - First30.ai',
          text: generateSummaryText(),
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      handleCopy();
    }
  };

  return (
    <div className="glass-card-strong p-6 md:p-8 print:bg-white print:text-black">
      {/* Header */}
      <div className="flex items-start justify-between mb-6">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 rounded-2xl bg-primary/20 flex items-center justify-center">
            <IconComponent className="w-8 h-8 text-primary" />
          </div>
          <div>
            <h2 className="text-heading-3 text-foreground">{data.category}</h2>
            <p className="text-sm text-muted-foreground">Emergency Summary</p>
          </div>
        </div>
        <PriorityBadge priority={data.priority} />
      </div>

      {/* Details Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
        <div className="glass-card p-4">
          <div className="flex items-center gap-2 text-muted-foreground mb-1">
            <Clock className="w-4 h-4" />
            <span className="text-sm">Duration</span>
          </div>
          <p className="text-lg font-semibold text-foreground">
            {formatDuration(data.duration)}
          </p>
        </div>

        <div className="glass-card p-4">
          <div className="flex items-center gap-2 text-muted-foreground mb-1">
            <CheckCircle2 className="w-4 h-4" />
            <span className="text-sm">Steps Completed</span>
          </div>
          <p className="text-lg font-semibold text-foreground">
            {data.stepsCompleted.length} of {data.totalSteps}
          </p>
        </div>

        <div className="glass-card p-4">
          <div className="flex items-center gap-2 text-muted-foreground mb-1">
            <Clock className="w-4 h-4" />
            <span className="text-sm">Start Time</span>
          </div>
          <p className="text-lg font-semibold text-foreground">
            {formatTime(data.startTime)}
          </p>
        </div>

        <div className="glass-card p-4">
          <div className="flex items-center gap-2 text-muted-foreground mb-1">
            <MapPin className="w-4 h-4" />
            <span className="text-sm">Location</span>
          </div>
          <p className="text-lg font-semibold text-foreground">
            {data.location || 'Not specified'}
          </p>
        </div>
      </div>

      {/* Completed Steps */}
      {data.stepsCompleted.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-medium text-muted-foreground mb-3">Steps Completed:</h3>
          <div className="flex flex-wrap gap-2">
            {data.stepsCompleted.map((step, index) => (
              <span
                key={step}
                className="px-3 py-1 rounded-full bg-success/20 text-success text-sm"
              >
                Step {index + 1} ✓
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-3 print:hidden">
        <Button
          onClick={handleShare}
          className="flex-1 h-12 bg-primary hover:bg-primary/90 rounded-xl"
        >
          <Share2 className="w-5 h-5 mr-2" />
          Share with Responders
        </Button>
        <Button
          onClick={handleCopy}
          variant="outline"
          className="flex-1 h-12 rounded-xl"
        >
          <Copy className="w-5 h-5 mr-2" />
          Copy
        </Button>
        <Button
          onClick={handlePrint}
          variant="outline"
          className="h-12 rounded-xl"
        >
          <Printer className="w-5 h-5" />
        </Button>
      </div>

      {/* New Emergency Button */}
      <div className="mt-4 pt-4 border-t border-border print:hidden">
        <Button
          onClick={onNewEmergency}
          variant="ghost"
          className="w-full h-12 text-muted-foreground hover:text-foreground"
        >
          Start New Emergency
        </Button>
      </div>
    </div>
  );
};

export default SummaryCard;
